import React from "react";
import "./appDesc.css";
import { titles, descriptions } from "./data";
import ImgCard from "../imageCard/imgCard";
import image1 from "../../assets/1.png";
import image2 from "../../assets/2.png";
import image3 from "../../assets/3.png";
import image4 from "../../assets/4.png";
import image5 from "../../assets/5.png";
import image6 from "../../assets/6.png";
import image7 from "../../assets/7.png";
import image8 from "../../assets/8.png";

const AppDescriptionPage = () => {
  return (
    <div className="app-desc-container border border-white border-opacity-20 bg-black bg-opacity-5 bg-transparent backdrop-filter backdrop-blur-2xl w-full flex flex-col items-center gap-10 lg:gap-20 p-10  xl:p-20 rounded-3xl">
      <h1 className="text-4xl md:text-6xl underline decoration-2 text-center">
        Ensuring CPT Code Accuracy with <br /> GoCPT App
      </h1>
      <div className="card-grid grid grid-cols-1 xl:grid-cols-3 gap-14 p-3 lg:p-10 xl:p-0 place-items-center content-center ">
        <ImgCard title={titles[0]} desc={descriptions[0]} cardImg={image1} />
        <ImgCard title={titles[1]} desc={descriptions[1]} cardImg={image4} />
        <ImgCard title={titles[2]} desc={descriptions[2]} cardImg={image5} />
        <ImgCard title={titles[3]} desc={descriptions[3]} cardImg={image2} />
        <ImgCard title={titles[4]} desc={descriptions[4]} cardImg={image3} />
        <ImgCard title={titles[5]} desc={descriptions[5]} cardImg={image6} />
        <ImgCard title={titles[6]} desc={descriptions[6]} cardImg={image7} />
        <ImgCard title={titles[7]} desc={descriptions[7]} cardImg={image8} />
      </div>
      <p className="text-base text-center">
        By incorporating these tips into your practice, you can maximize the
        accuracy of CPT codes generated by the goCPT app. Remember, your
        detailed and precise <br /> documentation is instrumental in optimizing
        the app's capabilities and contributing to the overall success of your
        medical coding and billing processes
      </p>
    </div>
  );
};

export default AppDescriptionPage;
